#################################################
## Rasterizing outbreak and breading dataframes
#################################################

source("src/Open.R")


# Outbreaks 
    # Need Smarter way to do this?
outbreaks <- full[110:nrow(full),]

month <- seq(1:12)
cla <- unique(outbreaks$Class)

c.spltr <- function(df, class){
  # function to seperate dataframes based on Class
  df.class <- filter(df, Class == class)
  return(df.class)
}

m.spltr <- function(df, month){
  #Function to seperate dataframe by month of occurence, and then by class of occurence
  df.month <- filter(df, M.Start == month)
  df.class <- lapply(cla, c.spltr, df = df.month)
  return(df.class)
}

ob.m <- lapply(month, m.spltr, df=outbreaks)


rast.inner <- function(idx.df){
  #Function for rasterizing the dataframes generated by m.spltr
  coordinates(idx.df) <- ~ lon +lat
  rast.df <- rasterize(idx.df, afr.blnk, field=1, fun='count', mask=T)
  rast.df@data@names <- idx.df$Class
  return(rast.df)
}

rast.middle <- function(m.ls){
  #Function to apply rast.inner to the lowest level created by m.spltr and removing null data
  m.ls <- m.ls[sapply(m.ls, function(x) dim(x)[1]) > 0]
  list.rast <- lapply(m.ls, rast.inner)
  return(list.rast)
}

outbreak.rasters <- lapply(ob.m, rast.middle)
outbreak.stacks <- lapply(outbreak.rasters, stack)
#Renaming layers
for( i in 1:length(outbreak.stacks)){
  tmp <- names(outbreak.stacks[[i]])
  tmp <- unlist(lapply(tmp, paste0, ".", i))
  tmp <- unlist(lapply(tmp, str_replace, "X", "Y"))
  names(outbreak.stacks[[i]]) <- tmp 
}
#Filling Gaps
Y <- c("Y2.1","Y3.1", "Y5.1",
       "Y2.2", "Y3.2","Y5.2",
       "Y2.3", "Y3.3", "Y5.3", "Y6.3",  
       "Y1.4","Y2.4", "Y3.4", "Y5.4",
       "Y2.5", "Y3.5", "Y5.5",
       "Y2.6", "Y3.6", "Y5.6",
       "Y1.7", "Y2.7", "Y3.7",
       "Y1.8", "Y2.8", "Y3.8", "Y5.8",
       "Y1.9", "Y2.9", "Y3.9", "Y5.9", "Y6.9", 
       "Y2.10", "Y3.10", "Y5.10",
       "Y1.11", "Y2.11", "Y3.11",
       "Y1.12", "Y2.12", "Y3.12","Y5.12")
dummY <- matrix(nrow = ncell(afr.blnk), ncol = length(Y))
colnames(dummY) <- Y
outbreak.df <- as.data.frame(cbind(as.data.frame(stack(outbreak.stacks)), dummY))

write.csv(outbreak.df, "data/Dataframes/cache/OBmatrix_long.csv", row.names = F)

## same thing for breeding df
breed <- full[1:109,]
cla <- unique(breed$Class)

breed.m <- lapply(month, m.spltr, df=breed)

breed.rasters <- lapply(breed.m, rast.middle)
breed.stacks <- lapply(breed.rasters, stack)

#Renaming layers
for( i in 1:length(breed.stacks)){
  tmp <- names(breed.stacks[[i]])
  tmp <- unlist(lapply(tmp, paste0, ".", i))
  names(breed.stacks[[i]]) <- tmp 
}

#Matching for breeding data
X <- c(
  "X3.1",
  "X3.2",
  "X3.3",
  "X2.4",
  "X3.5",
  "X3.6",
  "X3.7",
  "X3.8",
  "X2.9","X3.9",
  "X2.10")
dummX <- matrix(nrow = ncell(afr.blnk), ncol= length(X))
colnames(dummX) <- X
breed.df <- as.data.frame(cbind(as.data.frame(stack(breed.stacks)), dummX))

write.csv(breed.df, "data/Dataframes/cache/BRmatrix_long.csv", row.names = F)
